import {test} from 'node:test';
import assert from 'node:assert/strict';
import {artwork,defaults,kinds,sizes} from '../src/artwork.ts';
test('all pattern families and formats produce finite bounded SVG documents',()=>{for(const kind of kinds)for(const format of Object.keys(sizes))for(const mode of ['pattern','signal','poster','globe']){const svg=artwork({...defaults,kind,format,density:40,repeat:3,twist:300,scale:150},mode,123);assert.ok(svg.startsWith('<svg '));assert.ok(svg.endsWith('</svg>'));assert.ok(!/NaN|Infinity|undefined/.test(svg));assert.ok(svg.includes(`viewBox="0 0 ${sizes[format].join(' ')}"`));}});
test('poster escapes user text rather than creating markup',()=>{const svg=artwork({...defaults,headline:'<script> & "test"',caption:'<image href="x" />'},'poster');assert.ok(!svg.includes('<script>'));assert.ok(!svg.includes('<image'));assert.ok(svg.includes('&lt;SCRIPT&gt; &amp; &quot;TEST&quot;'));});
test('signal texture is reproducible and responds to seed and toggles',()=>{const a=artwork(defaults,'signal');assert.equal(a,artwork(defaults,'signal'));assert.notEqual(a,artwork({...defaults,seed:18},'signal'));assert.notEqual(a,artwork({...defaults,texture:0},'signal'));assert.ok(artwork({...defaults,chromatic:true},'signal').includes('#ff3866'));assert.ok(!artwork({...defaults,scanlines:false},'signal').includes('data-effect="scanlines"'));});
test('current rotation is included in static export',()=>{assert.ok(artwork({...defaults,rotation:20},'pattern',45).includes('rotate(65)'));});
test('pattern annotations can be omitted from the output',()=>{const labelled=artwork(defaults,'pattern');const clean=artwork({...defaults,annotations:false},'pattern');assert.ok(labelled.includes('data-effect="annotations"'));assert.ok(!clean.includes('data-effect="annotations"'));});
test('glitch overlay is available to every vector generator without requiring text',()=>{for(const mode of ['pattern','signal','poster','globe']){const clean=artwork({...defaults,glitchEnabled:false,textOverlay:false},mode);const glitched=artwork({...defaults,glitchEnabled:true,glitchAmount:48,textOverlay:false},mode);assert.ok(!clean.includes('data-effect="glitch-overlay"'));assert.ok(glitched.includes('data-effect="glitch-overlay"'));assert.notEqual(clean,glitched);}});
test('signal breakup is a separate text-free layer for every vector generator',()=>{for(const mode of ['pattern','signal','poster','globe']){const clean=artwork({...defaults,signalBreakup:false,textOverlay:false},mode);const broken=artwork({...defaults,signalBreakup:true,breakupDensity:32,textOverlay:false},mode);assert.ok(!clean.includes('data-effect="signal-breakup"'));assert.ok(broken.includes('data-effect="signal-breakup"'));assert.notEqual(clean,broken);}});
test('scanlines are a shared layer for every vector generator',()=>{for(const mode of ['pattern','signal','poster','globe']){const clean=artwork({...defaults,scanlines:false},mode);const scanned=artwork({...defaults,scanlines:true},mode);assert.ok(!clean.includes('data-effect="scanlines"'));assert.ok(scanned.includes('data-effect="scanlines"'));}});

const {thermalDefaults,thermalLUT,mapThermalPixels}=await import('../src/thermal.ts');
test('thermal blend at zero preserves original pixels and alpha',()=>{const pixels=new Uint8ClampedArray([20,60,180,120,230,200,10,255]);const original=pixels.slice();mapThermalPixels(pixels,{...thermalDefaults,blend:0});assert.deepEqual(pixels,original);});
test('thermal LUT maps luminance into multiple palette colours and reverses when inverted',()=>{for(const palette of ['spectrum','iron','acid']){const s={...thermalDefaults,palette,contrast:1,bands:64};const lut=thermalLUT(s),inverse=thermalLUT({...s,invert:true});assert.deepEqual([...lut.slice(0,3)],[...inverse.slice(765)]);assert.deepEqual([...lut.slice(765)],[...inverse.slice(0,3)]);assert.notDeepEqual([...lut.slice(300,303)],[...lut.slice(600,603)]);}});
test('posterization limits the number of heat colours',()=>{const lut=thermalLUT({...thermalDefaults,bands:4});const colours=new Set();for(let i=0;i<256;i++)colours.add([...lut.slice(i*3,i*3+3)].join(','));assert.equal(colours.size,4);});
test('heat mapping retains alpha and changes RGB based on brightness',()=>{const pixels=new Uint8ClampedArray([0,0,0,23,255,255,255,178]);mapThermalPixels(pixels,thermalDefaults);assert.equal(pixels[3],23);assert.equal(pixels[7],178);assert.notDeepEqual([...pixels.slice(0,3)],[...pixels.slice(4,7)]);});

const {projectPoint}=await import('../src/globe.ts');
test('globe projection preserves the sphere and differentiates front and back',()=>{const front=projectPoint(0,0,0,0),back=projectPoint(180,0,0,0);assert.equal(front[2],1);assert.equal(back[2],-1);for(const yaw of [-180,0,90])for(const tilt of [-80,0,80]){const point=projectPoint(37,51,yaw,tilt);assert.ok(Math.abs(point.reduce((s,v)=>s+v*v,0)-1)<1e-12);}});
test('globe rotation changes geometry while keeping labels escaped',()=>{const a=artwork({...defaults,globeLabel:'<WORLD> & TEST'},'globe');assert.ok(a.includes('data-asset="globe"'));assert.ok(a.includes('&lt;WORLD&gt; &amp; TEST'));assert.notEqual(a,artwork(defaults,'globe',60));assert.ok(a.includes('data-surface="back"'));});
test('glitch text is optional, escaped and slice-based',()=>{const s={...defaults,overlayText:'<SCRIPT>\nHELLO & WORLD',showPattern:false,textGlitch:60};const svg=artwork(s,'signal');assert.ok(svg.includes('&lt;SCRIPT&gt;'));assert.ok(svg.includes('HELLO &amp; WORLD'));assert.ok(svg.includes('data-effect="glitch-text"'));assert.ok(!svg.includes('<polygon'));assert.ok(!artwork({...s,textOverlay:false},'signal').includes('data-effect="glitch-text"'));assert.notEqual(svg,artwork({...s,textGlitch:0},'signal'));});
